#!/bin/bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

[ "${BUILD_ARCH}" == "Dockerfile" ] && \
    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }

case $BUILD_ARCH in
"arm64v8")
    echo "BUILD_ARCH::arm64v8 QEMU_USER_STATIC_ARCH::arm"
    QEMU_USER_STATIC_ARCH=arm
    ;;
"arm32v7")
    echo "BUILD_ARCH::arm32v7 QEMU_USER_STATIC_ARCH::arm"
    QEMU_USER_STATIC_ARCH=arm
    ;;
esac

QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"

QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

QEMU_STATIC_URL="${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz"

echo "Downloading qemu from :: ${QEMU_STATIC_URL}"

curl -SL ${QEMU_STATIC_URL} | tar xzv

echo "Workspace file list :: $(ls -lh)"